In [ ]:
sudo pip3 install numpy -U

#### Import the library

In [2]:
import numpy as np

#### Create the array

In [4]:
num = np.array([56,22,15,37,55,89,12])

In [5]:
print(num)

[56 22 15 37 55 89 12]


In [6]:
type(num)

numpy.ndarray

In [7]:
num.dtype

dtype('int64')

In [8]:
num.ndim

1

In [9]:
num[4]

55

In [10]:
num[4] = 67
num

array([56, 22, 15, 37, 67, 89, 12])

In [11]:
num[-1]

12

In [13]:
x = num[1:5]
print(x)

[22 15 37 67]


In [16]:
num = np.array([56,22,15,37,55,89,12],
              dtype=np.int16)

In [17]:
num

array([56, 22, 15, 37, 55, 89, 12], dtype=int16)

In [18]:
num.dtype

dtype('int16')

In [19]:
num = np.array([56,22,15.36,37,55,89,12])

In [20]:
num

array([56.  , 22.  , 15.36, 37.  , 55.  , 89.  , 12.  ])

In [21]:
num[3]

37.0

In [22]:
num.dtype

dtype('float64')

In [24]:
num = np.array([56,22,15,'hello',55,89,12])

In [25]:
num

array(['56', '22', '15', 'hello', '55', '89', '12'], dtype='<U21')

In [26]:
name = np.array(['परमेश्वर','मयंक','शुभांगी',
                 'भूमी','मेहेक','ऋषिकेश'])

In [27]:
name

array(['परमेश्वर', 'मयंक', 'शुभांगी', 'भूमी', 'मेहेक', 'ऋषिकेश'],
      dtype='<U8')

In [28]:
name[3]

'भूमी'

In [31]:
for x in name:
    if x.startswith('म'):
        print(x)

मयंक
मेहेक


#### Arithmetic Operations

In [33]:
num = np.array([12,43,38,66,38,28,24,92])

In [34]:
x = [12,43,38,66,38,28,24,92]

In [35]:
type(num), type(x)

(numpy.ndarray, list)

In [36]:
x * 2

[12, 43, 38, 66, 38, 28, 24, 92, 12, 43, 38, 66, 38, 28, 24, 92]

In [37]:
num * 2

array([ 24,  86,  76, 132,  76,  56,  48, 184])

In [38]:
num + 5

array([17, 48, 43, 71, 43, 33, 29, 97])

In [39]:
num /2

array([ 6. , 21.5, 19. , 33. , 19. , 14. , 12. , 46. ])

In [40]:
num > 30

array([False,  True,  True,  True,  True, False, False,  True])

In [41]:
num[num > 30]

array([43, 38, 66, 38, 92])

In [42]:
num[num%2==1]

array([43])

In [49]:
num1 = np.array([56,78,23,16,44,79])
num2 = np.array([32,93,23,29,38,19])

In [50]:
num1 + num2

array([ 88, 171,  46,  45,  82,  98])

In [51]:
num1 * num2

array([1792, 7254,  529,  464, 1672, 1501])

In [53]:
num1 / num2

array([1.75      , 0.83870968, 1.        , 0.55172414, 1.15789474,
       4.15789474])

In [54]:
num1 > num2

array([ True, False, False, False,  True,  True])

In [55]:
num1

array([56, 78, 23, 16, 44, 79])

In [56]:
num2

array([32, 93, 23, 29, 38, 19])

In [57]:
num1[num1==num2]

array([23])

In [58]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [61]:
np.arange(3,15,2)

array([ 3,  5,  7,  9, 11, 13])

In [62]:
np.arange(20,2,-2)

array([20, 18, 16, 14, 12, 10,  8,  6,  4])

In [63]:
np.arange(1,10,0.25)

array([1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 ,
       3.75, 4.  , 4.25, 4.5 , 4.75, 5.  , 5.25, 5.5 , 5.75, 6.  , 6.25,
       6.5 , 6.75, 7.  , 7.25, 7.5 , 7.75, 8.  , 8.25, 8.5 , 8.75, 9.  ,
       9.25, 9.5 , 9.75])

In [64]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [65]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

#### Matrix

In [67]:
mat = np.array([[4,7,2],[7,2,0]])

In [68]:
mat

array([[4, 7, 2],
       [7, 2, 0]])

In [69]:
mat.shape

(2, 3)

In [70]:
mat.size

6

In [71]:
mat+5

array([[ 9, 12,  7],
       [12,  7,  5]])

In [72]:
mat.reshape(3,2)

array([[4, 7],
       [2, 7],
       [2, 0]])

In [73]:
mat

array([[4, 7, 2],
       [7, 2, 0]])

In [74]:
mat.reshape(6,1)

array([[4],
       [7],
       [2],
       [7],
       [2],
       [0]])

In [75]:
mat.reshape(6)

array([4, 7, 2, 7, 2, 0])

In [76]:
num

array([12, 43, 38, 66, 38, 28, 24, 92])

In [77]:
num.min()

12

In [78]:
num.max()

92

In [79]:
num.mean()

42.625

In [81]:
num.sum()

341

In [82]:
num.sort()

In [83]:
num

array([12, 24, 28, 38, 38, 43, 66, 92])

In [86]:
num.sort()

In [87]:
num

array([12, 24, 28, 38, 38, 43, 66, 92])

In [88]:
np.sqrt(num)

array([3.46410162, 4.89897949, 5.29150262, 6.164414  , 6.164414  ,
       6.55743852, 8.1240384 , 9.59166305])

In [89]:
np.log(num)

array([2.48490665, 3.17805383, 3.33220451, 3.63758616, 3.63758616,
       3.76120012, 4.18965474, 4.52178858])